version: '3.1'

services:

  registration-history-service:
  build: .
  restart: always
  container_name: registration-history-service
  ports:
    - 7000:7000
  working_dir: /app
  depends_on:
    - mongodb
  networks:
    - registration-history-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: registry
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
      MONGO_INITDB_DATABASE: registration_history_service
    ports:
      - 27017:27017
    volumes:
      - ./src/resources/db/V1__create_user.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - registration-history-network
    command: ["--bind_ip_all"]

networks:
  registration-history-network:
    driver: bridge
